send_command:
  description: Send a raw command to the toiletlid.
  fields:
    entity_id:
      description: Name of the toiletlid entity.
      example: "toiletlid.my_xjx_toilet_pro"
    command:
      description: Command to execute.
      example: "func_off"
    params:
      description: Raw parameters for the command.
      example: ['night_led']

self_clean_on:
  description: Turn self clean on.
  fields:
    entity_id:
      description: Name of the toiletlid entity.
      example: "toiletlid.my_xjx_toilet_pro"

self_clean_off:
  description: Turn self clean off.
  fields:
    entity_id:
      description: Name of the toiletlid entity.
      example: "toiletlid.my_xjx_toilet_pro"

led_on:
  description: Turn led on.
  fields:
    entity_id:
      description: Name of the toiletlid entity.
      example: "toiletlid.my_xjx_toilet_pro"

led_off:
  description: Turn led off.
  fields:
    entity_id:
      description: Name of the toiletlid entity.
      example: "toiletlid.my_xjx_toilet_pro"
